package com.mosambee.notification_sdk.enumeration

enum class ResultAction {
    DEVICE_REGISTRATION_FAILED, INVALID_REQUEST, NOTIFICATION_CONNECTION_FAILED, SUBSCRIBE_TO_TOPIC_FAILED, CONNECTION_LOST, SOMETHING_WENT_WRONG
}